- name: Install java
  apt:
    name: openjdk-11-jre-headless
    state: present
    
- name: Install other soft
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - uuid-runtime
    - pwgen
    - dirmngr
    - gnupg
    - apt-transport-https